# Generated by `mda build` — do not edit.
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from managed_deepagents.runtime import build_managed_http_app

from _mda_connectors import connectors as _connectors
from identity import identity as _identity
from src.tools.pylon_tools import check_pylon_credentials


@asynccontextmanager
async def _lifespan(_app) -> AsyncIterator[None]:
    check_pylon_credentials()
    yield


app = build_managed_http_app(identity=_identity, connectors=_connectors)
app.router.lifespan_context = _lifespan
