# Generated by `mda build` — do not edit.
from managed_deepagents.runtime import build_managed_http_app

from _mda_connectors import connectors as _connectors
from identity import identity as _identity

app = build_managed_http_app(identity=_identity, connectors=_connectors)
