# Generated by `mda build` — do not edit.
from managed_deepagents.runtime import collect_connectors

import connectors.langsmith as _connector0
import connectors.mcp as _connector1

connectors = collect_connectors(
    [
        ("connectors/langsmith.py", _connector0),
        ("connectors/mcp.py", _connector1),
    ]
)
