WEAVIATE_DOCS_INDEX_NAME = "LangChain_Combined_Docs_OpenAI_text_embedding_3_small"

WEAVIATE_GENERAL_GUIDES_AND_TUTORIALS_INDEX_NAME = "LangChain_General_Guides_And_Tutorials_OpenAI_text_embedding_3_small"

WEAVIATE_LANGCHAIN_PYTHON_SDK_INDEX_NAME = "LangChain_Python_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGCHAIN_JS_SDK_INDEX_NAME = "LangChain_JS_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGGRAPH_PYTHON_SDK_INDEX_NAME = "LangGraph_Python_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGGRAPH_JS_SDK_INDEX_NAME = "LangGraph_JS_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGGRAPH_PLATFORM_API_INDEX_NAME = "LangGraph_Platform_API_OpenAI_text_embedding_3_small"
WEAVIATE_LANGSMITH_PYTHON_SDK_INDEX_NAME = "LangSmith_Python_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGSMITH_JS_SDK_INDEX_NAME = "LangSmith_JS_SDK_OpenAI_text_embedding_3_small"
WEAVIATE_LANGSMITH_API_INDEX_NAME = "LangSmith_API_OpenAI_text_embedding_3_small"